global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'codetime-backend'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/metrics'

  - job_name: 'codetime-worker'
    static_configs:
      - targets: ['worker:3000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'timescale'
    static_configs:
      - targets: ['timescale:5432']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092'] 